db:
  pc_customer:
    password: cGNfY3VzdG9tZXIxNDM=
  pc_visit:
    password: cGNfdmlzaXQxNDM=
  pc_vet:
    password: cGNfdmV0MTQz

postgresql:
  enabled: true
  fullnameOverride: postgresql

  primary:
    extendedConfiguration: |
      max_connections = 40
      shared_buffers = 1GB
      effective_cache_size = 3GB
      maintenance_work_mem = 256MB
      checkpoint_completion_target = 0.9
      wal_buffers = 16MB
      default_statistics_target = 100
      random_page_cost = 1.1
      effective_io_concurrency = 200
      work_mem = 13107kB
      huge_pages = off
      min_wal_size = 1GB
      max_wal_size = 4GB
    extraEnvVars:
      - name: PC_VET_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pc-vet-db-secret
            key: DB_PASSWORD
      - name: PC_CUSTOMER_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pc-customer-db-secret
            key: DB_PASSWORD
      - name: PC_VISIT_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pc-visit-db-secret
            key: DB_PASSWORD

    initdb:
      scripts:
        00_create_users.sh: |
          #!/bin/sh
          echo "Running pre-initialization tasks..."
          
          export PGPASSWORD=$POSTGRESQL_INITSCRIPTS_PASSWORD
          
          psql -c "CREATE USER pc_customer PASSWORD '${PC_CUSTOMER_DB_PASSWORD}'"
          psql -c "CREATE USER pc_vet PASSWORD '${PC_VET_DB_PASSWORD}'"
          psql -c "CREATE USER pc_visit PASSWORD '${PC_VISIT_DB_PASSWORD}'"
        02_create_databases.sql: |
          CREATE DATABASE pc_customer OWNER pc_customer;
          CREATE DATABASE pc_vet OWNER pc_vet;
          CREATE DATABASE pc_visit OWNER pc_visit;
