apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.profiles }}"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              {{ if .Values.eureka.client.defaultZone.value }}
              value: {{.Values.eureka.client.defaultZone.value }}
              {{ else if .Values.eureka.client.defaultZone.valueFrom}}
              valueFrom:
                {{- toYaml .Values.eureka.client.defaultZone.valueFrom | nindent 16}}
              {{ end }}
            - name: EUREKA_INSTANCE_PREFERIPADDRESS
              value: "true"
            - name: GIT_SEARCH_PATHS
              value: "{{ .Values.git.search.paths }}"
            - name: ENCRYPT_KEYSTORE_LOCATION
              value: "file:/workspace/keystore/keystore"
            - name: ENCRYPT_KEYSTORE_ALIAS
              value: "{{ .Values.encrypt.keystore.alias }}"
            - name: ENCRYPT_KEYSTORE_PASSWORD
              {{ if .Values.encrypt.keystore.password.value }}
              value: {{.Values.encrypt.keystore.password.value }}
              {{ else if .Values.encrypt.keystore.password.valueFrom}}
              valueFrom:
                {{- toYaml .Values.encrypt.keystore.password.valueFrom | nindent 16}}
              {{ end }}
            {{ if .Values.logging.structured.enabled }}
            - name: LOGGING_STRUCTURED_FORMAT_CONSOLE
              value: "{{ .Values.logging.structured.format.console }}"
            {{ end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.liveness.delay }}
            periodSeconds: {{ .Values.liveness.timeout }}
            failureThreshold: 10
            httpGet:
              path: {{ .Values.liveness.path }}
              port: http
          readinessProbe:
            initialDelaySeconds: {{ .Values.readiness.delay }}
            periodSeconds: {{ .Values.readiness.timeout }}
            failureThreshold: 10
            httpGet:
              path: {{ .Values.readiness.path }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: keystore-volume
              mountPath: /workspace/keystore
              readOnly: true
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: keystore-volume
          secret:
            secretName: {{ include "app.fullname" . }}-keystore
            items:
              - key: keystore
                path: keystore
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
