{{- if .Values.keystore.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-keystore-password
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  keystore-password: {{ .Values.keystore.password | b64enc }}
{{- end }}
