{{- if .Values.keystore.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-keystore
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.keystore.filePath }}
  {{ .Values.keystore.key }}: {{ .Files.Get .Values.keystore.filePath | b64enc }}
  {{- end }}
{{- end }}
