apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-keystore
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  keystore: {{ .Files.Get .Values.keystore.filePath | b64enc }}
