spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: false
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
        - name: Retry
          args:
            retries: 1
            statuses: SERVICE_UNAVAILABLE
            methods: POST
      routes:
        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: genai-service
          uri: lb://genai-service
          predicates:
            - Path=/api/genai/**
          filters:
            - StripPrefix=2
            - CircuitBreaker=name=genaiCircuitBreaker,fallbackUri=/fallback
      discovery:
        locator:
          enabled: true

# Internationalization
spring.messages.basename: messages/messages

eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    enabled: false
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

logging.level.org.springframework: INFO

logging.level.org.springframework.cloud.gateway: DEBUG
logging.level.org.springframework.cloud.loadbalancer: DEBUG

---
spring:
  config:
    activate:
      on-profile: discovery

eureka:
  client:
    enabled: true


---
spring:
  config:
    activate:
      on-profile: cloudconfig
  cloud:
    config:
      enabled: true
