spring:
  application:
    name: discovery-server
  profiles:
    group:
      dev:
        - standalone
        - local
      compose:
        - standalone
      prod:
        - cluster

server:
  port: 8761

management:
  endpoint:
    configprops:
      show-values: always
  endpoints:
    web:
      exposure:
        include: health,info,configprops

# Avoid some debugging logs at startup
logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO


---
spring:
  config:
    activate:
      on-profile: standalone

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  config:
    activate:
      on-profile: cluster

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULTZONE}
