spring:
  main:
    web-application-type: reactive
  application:
    name: genai-service
  profiles:
    group:
      dev-local:
        - postgres
        - local
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: false
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server
  ai:
    chat:
      client:
        enabled: true
    # These apply when using spring-ai-azure-openai-spring-boot-starter
    azure:
      openai:
        api-key: ${AZURE_OPENAI_KEY}
        endpoint: ${AZURE_OPENAI_ENDPOINT}
        chat:
          options:
            temperature: 0.7
            deployment-name: gpt-4o
    # These apply when using spring-ai-openai-spring-boot-starter
    openai:
      chat:
        options:
            temperature: 0.7
            model: gpt-4o-mini

eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

logging.level.org.springframework: INFO

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

---
spring:
  config:
    activate:
      on-profile: discovery

eureka:
  client:
    enabled: true


---
spring:
  config:
    activate:
      on-profile: cloudconfig
  cloud:
    config:
      enabled: true
