spring:
  main:
    web-application-type: reactive
  application:
    name: genai-service
  profiles:
    group:
      dev:
        - openai
        - local
      sdev:
        - openai
        - standalone
        - local
      compose:
        - openai
        - standalone
        - cloudconfig
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: false
      fail-fast: true
      discovery:
        service-id: config-server
        enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  ai:
    chat:
      client:
        enabled: true
    azure:
      openai:
        embedding:
          enabled: false
        chat:
          enabled: false
    openai:
      embedding:
        enabled: false
      chat:
        enabled: false

eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    enabled: false


logging.level.org.springframework: INFO

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

---
spring:
  config:
    activate:
      on-profile: azureai
  ai:
    azure:
      embedding:
        enabled: true
      openai:
        chat:
          enabled: true
          options:
            temperature: 0.7
            deployment-name: gpt-4o

---
spring:
  config:
    activate:
      on-profile: openai
  ai:
    openai:
      embedding:
        enabled: true
      chat:
        enabled: true
        options:
          temperature: 0.7
          model: gpt-4o-mini
    azure:
      openai:
        # just to make possible having in classpath azure and openai starters
        open-ai-api-key: noope

---
spring:
  config:
    activate:
      on-profile: standalone
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost:8761}/eureka/

---
spring:
  config:
    activate:
      on-profile: cloudconfig
  cloud:
    config:
      enabled: true
