eureka:
  fullnameOverride: discovery-server
  replicaCount: 3
  image:
    repository: spring-petclinic-discovery-server
    tag: 3.4.1
  statefulset:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: EUREKA_INSTANCE_HOSTNAME
      value: $(POD_NAME).$(SUBDOMAIN)
    - name: EUREKA_CLIENT_DEFAULTZONE
      value: $(EUREKA_ADDRESS_LIST)
