spring:
  application:
    name: customers-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  profiles:
    group:
      dev-local:
        - postgres
        - local
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: false
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server

eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    enabled: false
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

logging.level.org.springframework: INFO

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}/${POSTGRES_DB_NAME:pc_customer}
    username: ${POSTGRES_USERNAME:petclinic}
    password: ${POSTGRES_PASSWORD:petclinic}
  sql:
    init:
      schema-locations: classpath*:db/postgres/schema.sql
      data-locations: classpath*:db/postgres/data.sql
      mode: ALWAYS

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/petclinic?useSSL=false
    username: root
    password: petclinic
  sql:
    init:
      schema-locations: classpath*:db/mysql/schema.sql
      data-locations: classpath*:db/mysql/data.sql
      mode: ALWAYS

---
spring:
  config:
    activate:
      on-profile: hsql
  sql:
    init:
      schema-locations: classpath*:db/hsqldb/schema.sql
      data-locations: classpath*:db/hsqldb/data.sql

---
spring:
  config:
    activate:
      on-profile: discovery

eureka:
  client:
    enabled: true


---
spring:
  config:
    activate:
      on-profile: cloudconfig
  cloud:
    config:
      enabled: true
