csi:
  provisionerName: network-drives.csi.timeweb.cloud
  # plugin container image options
  image:
    # image name
    repository: registry-tw-csi.twc1.net/csi-driver/driver
    # image tag
    tag: latest
    # image pull policy
    pullPolicy: Always

  # Node service options
  node:
    # node service log level
    logLevel: debug
    # force logs as json
    logJson: true

  # Controller service options
  controller:
    # controller replica count
    replicas: 1

    # controller node selector
    nodeSelector: {}

    # controller toleration options
    tolerations: []

  # RBAC options
  rbac:
    createRoles: true
    createServiceAccounts: true

  # metrics options
  metrics:
    podMonitor:
      enabled: false
      port: metrics
      path: /metrics
      interval: 60s
