spring:
  application:
    name: config-server
  profiles:
    group:
      dev:
        - git
        - local
      sdev:
        - git
        - local
        - discovery
      compose:
        - git
        - icompose
        - discovery
      prod:
        - git
        - discovery
        - iprod

  cloud:
    config:
      allow-override: true
      server:
        git:
          uri: ${GIT_CONFIG_URI:https://gitflic.ru/project/ikuchmin/spring-petclinic-microservices-config.git}
          default-label: ${GIT_CONFIG_LABEL:master}
          search-paths: ${GIT_CONFIG_SEARCH_PATHS}

server:
  port: 8888

encrypt:
  key-store:
    location:
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    enabled: false

management:
  endpoint:
    configprops:
      show-values: always
  endpoints:
    web:
      exposure:
        include: health,info,configprops

---
spring:
  config:
    activate:
      on-profile: discovery

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULTZONE}
