spring:
  application:
    name: config-server

server:
  port: 8888

eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    enabled: false
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

---

spring:
  config:
    activate:
      on-profile: discovery

eureka:
  client:
    enabled: true
