spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI:https://gitflic.ru/project/ikuchmin/spring-petclinic-microservices-config.git}
          default-label: ${GIT_DEFAULT_LABEL:demo5}
          search-paths: ${GIT_SEARCH_PATHS:/production}

eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    enabled: false
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

server:
  port: 8888

---
spring:
  config:
    activate:
      on-profile: discovery
eureka:
  client:
    enabled: true
