cert-manager:
  namespace: cert-manager
  crds:
    enabled: false
#  global:
#    logLevel: 6
letsencrypt:
  ingressClassName: nginx
  staging:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ikuchmin@demo8.spring-petclinic.ru
  prod:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ikuchmin@demo8.spring-petclinic.ru
