CREATE TABLE IF NOT EXISTS vets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  first_name VARCHAR,
  last_name VARCHAR,
  CONSTRAINT pk_vets PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS specialties (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR,
  CONSTRAINT pk_specialties PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS vet_specialties (
  specialty_id INTEGER NOT NULL,
  vet_id INTEGER NOT NULL,
  CONSTRAINT pk_vet_specialties PRIMARY KEY (specialty_id, vet_id)
);

ALTER TABLE vet_specialties DROP CONSTRAINT IF EXISTS fk_vetspe_on_specialty;
ALTER TABLE vet_specialties ADD CONSTRAINT fk_vetspe_on_specialty FOREIGN KEY (specialty_id) REFERENCES specialties (id);

ALTER TABLE vet_specialties DROP CONSTRAINT IF EXISTS fk_vetspe_on_vet;
ALTER TABLE vet_specialties ADD CONSTRAINT fk_vetspe_on_vet FOREIGN KEY (vet_id) REFERENCES vets (id);
