apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-pc-visit-db-secret
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.db.pc_visit.password }}
